apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pgrestores.postgresql.operator.com
spec:
  group: postgresql.operator.com
  names:
    kind: PgRestore
    listKind: PgRestoreList
    plural: pgrestores
    singular: pgrestore
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
